FiveTeam/Areas/AdminHome/Controllers/AdminReviewController.cs
using FiveTeam.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FiveTeam.Areas.AdminHome.Controllers
{
    public class AdminReviewController : Controller
    {
        QuanLySanPhamEntities2 db = new QuanLySanPhamEntities2();

        // GET: Review
        public ActionResult Review()
        {
            return View(db.ReviewFiveTeams.ToList());
        }
        public ActionResult ListReview()
        {

            return View(db.ReviewFiveTeams.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(ReviewFiveTeam review, HttpPostedFileBase fileAnh)
        {
            QuanLySanPhamEntities2 db = new QuanLySanPhamEntities2();
            if (ModelState.IsValid)
            {
                if (fileAnh != null && fileAnh.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(fileAnh.FileName);
                    string filePath = Path.Combine(Server.MapPath("~/img/Products/"), fileName);
                    fileAnh.SaveAs(filePath);
                    review.Picture = "~/img/Products/" + fileName;
                }
                db.ReviewFiveTeams.Add(review);
                db.SaveChanges();

                return RedirectToAction("ListReview");
            }
            return View(review);
        }



        /* sửa sản phẩm*/
        public ActionResult Edit(int id)
        {
            QuanLySanPhamEntities2 db = new QuanLySanPhamEntities2();

            ReviewFiveTeam review = db.ReviewFiveTeams.Find(id);
            return View(review);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NameReview,ContentReview,Picture,Start")] ReviewFiveTeam review, HttpPostedFileBase fileAnh)
        {
            QuanLySanPhamEntities2 db = new QuanLySanPhamEntities2();
            if (ModelState.IsValid)
            {
                if (fileAnh != null && fileAnh.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(fileAnh.FileName);
                    string filePath = Path.Combine(Server.MapPath("~/img/Review/"), fileName);
                    fileAnh.SaveAs(filePath);
                    review.Picture = "~/img/Review/" + fileName;
                }

                db.Entry(review).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListReview");
            }

            return View(review);
        }


        /* Xóa sản phẩm*/
        public ActionResult Delete(int id)
        {
            QuanLySanPhamEntities2 db = new QuanLySanPhamEntities2();
            var updateModel = db.ReviewFiveTeams.Find(id);
            db.ReviewFiveTeams.Remove(updateModel);
            db.SaveChanges();

            return RedirectToAction("ListReview");
        }


        // Chi tiết sản phẩm/
        public ActionResult Details(int? id)
        {
            QuanLySanPhamEntities2 db = new QuanLySanPhamEntities2();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ReviewFiveTeam review = db.ReviewFiveTeams.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }

            return View(review);
        }

    }
}

FiveTeam/Areas/AdminHome/Views/AdminReview/Create.cshtml
@model FiveTeam.Models.ReviewFiveTeam

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminHome/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Các thuộc tính chung */
    .heading {
        font-weight: bolder;
        text-align: center;
        padding: 5rem 0 2rem; /* Kết hợp padding thành một dòng */
        font-size: 3.5rem;
        color: var(--black);
    }

        /* Hiệu ứng cho phần chữ trong thẻ <span> của .heading */
        .heading span {
            background: #FF8C00;
            color: #fff;
            display: inline-block;
            padding: .5rem 3rem;
            clip-path: polygon(100% 0, 93% 50%, 100% 99%, 0% 100%, 7% 50%, 0% 0%);
        }

    /* Phần form */
    .form-horizontal, h2, h4 {
        width: 60%;
        margin: 0 auto;
        line-height: 1.5rem;
        border-radius: .5rem;
        background: #eee;
        color: var(--black);
        font-size: 1.5rem;
        font-weight: bolder;
    }

    .form-group {
        margin-bottom: 10px;
    }

    .control-label {
        text-align: right;
    }

    .col-md-10 {
        padding: 0;
    }

    .form-control {
        background-color: #eee;
        font-size: 1.5rem;
        width: 90%;
    }

        .form-control:hover {
            color: var(--orange); /* Loại bỏ dòng trùng lặp */
            cursor: pointer;
        }

    /* Nút */
    .btn-default {
        padding: 0.5rem 1rem;
        font-size: 1.5rem;
        border-radius: 0.5rem;
        font-weight: bolder;
        color: #FF8C00;
    }

        /* Hover state cho nút */
        .btn-default:hover {
            background-color: var(--orange);
        }

    h3 {
        width: 60%;
        margin: 0 auto;
        font-size: 3rem;
        font-weight: bolder;
        color: #FF8C00;
    }

    /* Đặt màu chữ cho nút */
    .btn-default {
        color: #FF8C00;
    }
</style>
<h1 class="heading" style="color: #000080"> Tạo <span>Đánh Giá</span> </h1>
<h3>Gia Vị Việt</h3>

@using (Html.BeginForm("Create", "AdminReview", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="color: #000080">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameReview, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameReview, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameReview, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContentReview, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentReview, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContentReview, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="fileAnh" class="form-control" />
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
            <div class="col-md-offset-2 ">
                @Html.ActionLink("Back to List", "ListReview", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

FiveTeam/Areas/AdminHome/Views/AdminReview/Delete.cshtml
@model FiveTeam.Models.ReviewFiveTeam

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/AdminHome/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NameReview)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameReview)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentReview)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentReview)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ListReview")
        </div>
    }
</div>

FiveTeam/Areas/AdminHome/Views/AdminReview/Details.cshtml
@model FiveTeam.Models.ReviewFiveTeam

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/AdminHome/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    /* CSS cho tiêu đề */
    .heading {
        font-weight: bolder; /* Đặt độ đậm cho font */
        text-align: center; /* Canh giữa */
        padding: 2rem 0; /* Padding trên và dưới */
        padding-top: 5rem; /* Thêm padding trên */
        font-size: 3.5rem; /* Kích thước font */
        color: var(--black); /* Màu chữ */
    }

        /* Hiệu ứng cho phần chữ trong thẻ <span> của .heading */
        .heading span {
            background: #FF8C00; /* Màu nền */
            color: #fff; /* Màu chữ */
            display: inline-block; /* Hiển thị như một khối */
            padding: .5rem 3rem; /* Padding cho span */
            clip-path: polygon(100% 0, 93% 50%, 100% 99%, 0% 100%, 7% 50%, 0% 0%); /* Định dạng dạng hình */
        }

    /* CSS cho danh sách chi tiết ngang */
    .dl-horizontal {
        width: 60%; /* Độ rộng của các thành phần form */
        margin: 0 auto; /* Canh giữa */
        line-height: 1.5rem; /* Chiều cao dòng */
        border-radius: .5rem; /* Bo tròn góc */
        background: #eee; /* Màu nền */
        color: var(--black); /* Màu chữ */
        font-size: 1.5rem; /* Kích thước font */
        font-weight: bolder; /* Độ đậm cho font */
        align-items: center;
    }

    /* CSS cho nhóm form */
    .form-group {
        margin-bottom: 5px; /* Khoảng cách dưới */
    }

    /* CSS cho tiêu đề danh mục */
    dt {
        margin-bottom: 15px; /* Khoảng cách dưới */
        font-size: 1.5rem; /* Kích thước font */
        font-weight: bolder; /* Độ đậm cho font */
    }

    /* CSS cho nội dung danh mục */
    dd {
        margin-bottom: 10px; /* Khoảng cách dưới */
        font-size: 1.5rem; /* Kích thước font */
        cursor: pointer; /* Con trỏ chuột */
        margin-top: 15px; /* Khoảng cách trên */
    }

    /* CSS cho tiêu đề h3 */
    h3 {
        width: 60%; /* Độ rộng */
        margin: 0 auto; /* Canh giữa */
        font-size: 3rem; /* Kích thước font */
        color: #FF8C00; /* Màu chữ */
        font-weight: bolder; /* Độ đậm cho font */
    }

    /* CSS cho nút */
    .bnt {
        margin-top: .5rem; /* Khoảng cách trên */
        display: inline-block; /* Hiển thị inline-block */
        padding: .8rem 2rem; /* Padding */
        font-size: 1.7rem; /* Kích thước font */
        border-radius: .5rem; /* Bo tròn góc */
        cursor: pointer; /* Con trỏ chuột */
        background: none; /* Không có giá trị nền */
        font-weight: bolder; /* Độ đậm cho font */
        margin: 0 auto; /* Canh giữa */
    }

    /* CSS cho nút mặc định */
    .btn-default {
        padding: 0.5rem 1rem; /* Padding */
        font-size: 1.5rem; /* Kích thước font */
        border-radius: 0.5rem; /* Bo tròn góc */
        font-weight: bolder; /* Độ đậm cho font */
        color: #FF8C00; /* Màu chữ */
    }

    /* CSS cho nút khi hover */
    .bnt btn-default:hover {
        background-color: var(--orange); /* Màu nền hover */
        color: #FF8C00; /* Màu chữ hover */
    }
</style>
<h1 class="heading" style="color: #000080"> Thông Tin <span>Đánh Giá</span> </h1>
<h3>Gia Vị Việt</h3>

<div>
    <hr />
    <dl class="dl-horizontal" style="color: #000080">
        <dt>
            @Html.DisplayNameFor(model => model.NameReview)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameReview)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentReview)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentReview)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start)
        </dd>

    </dl>
    <div class="">
        <div class="col-md-6 col-md-offset-3 text-left">
            <!-- Sử dụng col-md-6 và col-md-offset-3 để căn giữa và giữ cùng một hàng -->
            <div class="text-center">
                <!-- Thêm text-center để căn giữa nội dung -->
                @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { @class = "btn btn-default" })
                @Html.ActionLink("Back to List", "ListReview", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

FiveTeam/Areas/AdminHome/Views/AdminReview/Edit.cshtml
@model FiveTeam.Models.ReviewFiveTeam

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminHome/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Các thuộc tính chung cho .heading */
    .heading {
        font-weight: bolder; /* Đặt độ đậm cho font */
        text-align: center; /* Canh giữa văn bản */
        font-size: 3.5rem; /* Kích thước font */
        color: var(--black); /* Màu chữ */
        padding: 5rem 0 2rem; /* Padding: trên dưới 5rem, bên trong 0, dưới 2rem */
    }

        /* Hiệu ứng cho phần chữ trong thẻ <span> của .heading */
        .heading span {
            background: #FF8C00; /* Màu nền cho span */
            color: #fff; /* Màu chữ cho span */
            display: inline-block; /* Hiển thị như một khối, không đẩy xuống dòng */
            padding: .5rem 3rem; /* Padding cho span */
            clip-path: polygon(100% 0, 93% 50%, 100% 99%, 0% 100%, 7% 50%, 0% 0%); /* Định dạng dạng hình */
        }

    /* Phần form */
    .form-horizontal {
        width: 50%; /* Độ rộng của các thành phần form */
        margin: 0 auto; /* Canh giữa */
        line-height: 1.5rem; /* Chiều cao dòng */
        border-radius: .5rem; /* Bo tròn góc */
        background: #eee; /* Màu nền */
        color: var(--black); /* Màu chữ */
        font-size: 1.5rem; /* Kích thước font */
        font-weight: bolder; /* Độ đậm cho font */

        align-items: center;
    }

    .form-group {
        margin-bottom: 10px; /* Khoảng cách dưới */
    }

    .control-label {
        text-align: right; /* Canh phải */
        margin-top: 10px; /* Khoảng cách trên */
    }

    .col-md-10 {
        padding: 0; /* Xóa padding */
        margin-bottom: 10px; /* Khoảng cách dưới */
    }

    .form-control {
        background-color: #eee; /* Màu nền cho control */
        font-size: 1.5rem; /* Kích thước font */
        width: 90%; /* Độ rộng */
    }

        .form-control:hover {
            color: var(--orange); /* Màu chữ hover */
            cursor: pointer; /* Con trỏ chuột */
        }

    /* Nút */
    .btn-default {
        padding: 0.5rem 1rem; /* Padding cho nút */
        font-size: 1.5rem; /* Kích thước font */
        border-radius: 0.5rem; /* Bo tròn góc */
        font-weight: bolder; /* Độ đậm cho font */
        color: #FF8C00; /* Màu chữ */
    }

        .btn-default:hover {
            background-color: var(--orange); /* Màu nền hover */
        }

    /* Nút .bnt */
    .bnt {
        margin-top: 1rem; /* Khoảng cách trên */
        display: inline-block; /* Hiển thị inline-block */
        padding: .8rem 3rem; /* Padding */
        font-size: 1.7rem; /* Kích thước font */
        border-radius: .5rem; /* Bo tròn góc */
        border: .2rem solid var(--black); /* Đường viền */
        cursor: pointer; /* Con trỏ chuột */
        background: none; /* Không có giá trị nền */
        font-weight: bolder; /* Độ đậm cho font */
    }

        .bnt:hover {
            background-color: var(--orange); /* Màu nền hover */
            color: #FF8C00; /* Màu chữ hover */
        }

    h3 {
        width: 50%; /* Độ rộng của tiêu đề h3 */
        margin: 0 auto; /* Canh giữa */
        font-size: 3rem; /* Kích thước font */
        font-weight: bolder; /* Độ đậm cho font */
        color: #FF8C00; /* Màu chữ */
    }
</style>

<h1 class="heading" style="color: #000080"> Sửa <span>Đánh Giá</span> </h1>
<h3>Gia Vị Việt</h3>

@using (Html.BeginForm("Edit", "AdminReview", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal" style="color: #000080">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.NameReview, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NameReview, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NameReview, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContentReview, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContentReview, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContentReview, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="fileAnh" class="form-control" />
            @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="">
        <div class="col-md-6 col-md-offset-3 text-left ">
            <div class="text-center">
                <input type="submit" value="Save" class="btn btn-default" />
                @Html.ActionLink("Back to List", "ListReview", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>
}

FiveTeam/Areas/AdminHome/Views/AdminReview/ListReview.cshtml
@model IEnumerable<FiveTeam.Models.ReviewFiveTeam>

@{
    ViewBag.Title = "ListReview";
    Layout = "~/Areas/AdminHome/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Định nghĩa các thuộc tính CSS cho class .heading */
    .heading {
        font-weight: bolder;
        text-align: center;
        font-size: 3.5rem;
        color: var(--black);
        padding: 5rem 0 2rem;
    }

        /* Tạo hiệu ứng nổi bật cho phần chữ trong thẻ <span> của .heading */
        .heading span {
            background: #FF8C00;
            color: #fff;
            display: inline-block;
            padding: .5rem 3rem;
            clip-path: polygon(100% 0, 93% 50%, 100% 99%, 0% 100%, 7% 50%, 0% 0%);
        }

    /* Định nghĩa các thuộc tính CSS cho class .alert */
    .alert {
        /* Thêm class alert-success vào đây */
        width: 60%;
        font-weight: bolder;
        color: #FF8C00;
    }

    /* Định nghĩa các thuộc tính CSS cho class .table-container và thẻ p */
    .table-container, p {
        width: 60%;
        margin: 0 auto;
    }

    /* Định nghĩa các thuộc tính CSS cho thẻ table */
    table {
        border-collapse: collapse;
        width: 100%;
    }

    /* Định nghĩa các thuộc tính CSS cho thẻ tr */
    tr {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    /* Định nghĩa các thuộc tính CSS cho thẻ th */
    th {
        font-weight: bolder;
        color: var(--black);
    }

    /* Định nghĩa các thuộc tính CSS cho thẻ td */
    td {
        color: var(--black);
    }

    /* Định nghĩa các thuộc tính CSS cho class .bnt */
    .bnt {
        margin-top: 1rem;
        display: inline-block;
        padding: .8rem 3rem;
        font-size: 1.7rem;
        border-radius: .5rem;
        border: .2rem solid var(--black);
        cursor: pointer;
        background:; /* Chưa có giá trị nền */
        font-weight: bolder;
    }

    /* Định nghĩa các thuộc tính CSS cho class .btn-default */
    .btn-default {
        padding: 0.5rem 1rem;
        font-size: 1.5rem;
        border-radius: 0.5rem;
        font-weight: bolder;
        color: #FF8C00;
    }

    /* Định nghĩa các thuộc tính CSS cho class .bnt btn-default khi hover */
    .bnt btn-default:hover {
        background-color: var(--orange);
        color: #FF8C00;
    }

    /* Định nghĩa các thuộc tính CSS cho thẻ h3 */
    h3 {
        width: 60%;
        margin: 0 auto;
        font-size: 3rem;
        font-weight: bolder;
        color: #FF8C00;
    }
</style>

<h1 class="heading" style="color: #000080"> Danh sách <span>Đánh Giá</span> </h1>
<h1 class="heading"> @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-default" }) </h1>
<h3>Gia Vị Việt</h3>
<div class="table-container" style="color: #000080">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NameReview)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContentReview)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Start)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NameReview)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContentReview)
                </td>
                <td>
                    <img src="@Url.Content(item.Picture)"
                         alt="Image"
                         width="100"
                         height="100" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Start)
                </td>
                <td class="default" style="text-align: right;">
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-default" })
                </td>
            </tr>
        }

    </table>
</div>