FiveTeam/Areas/AdminHome/Controllers/AdminCategoriesController.cs
using FiveTeam.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FiveTeam.Areas.AdminHome.Controllers
{
    public class AdminCategoriesController : Controller
    {
        QuanLySanPhamEntities2 db = new QuanLySanPhamEntities2();

        // GET: Categories
        public ActionResult Categories()
        {
            return View(db.CategoriesFiveTeams.ToList());
        }
        public ActionResult ListCategories()
        {
            return View(db.CategoriesFiveTeams.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(CategoriesFiveTeam categories, HttpPostedFileBase fileAnh)
        {
            QuanLySanPhamEntities2 db = new QuanLySanPhamEntities2();
            if (ModelState.IsValid)
            {
                if (fileAnh != null && fileAnh.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(fileAnh.FileName);
                    string filePath = Path.Combine(Server.MapPath("~/img/Categories/"), fileName);
                    fileAnh.SaveAs(filePath);
                    categories.Picture = "~/img/Categories/" + fileName;
                }
                db.CategoriesFiveTeams.Add(categories);
                db.SaveChanges();

                return RedirectToAction("ListCategories");
            }
            return View(categories);
        }


        /* sửa sản phẩm*/
        public ActionResult Edit(int id)
        {
            QuanLySanPhamEntities2 db = new QuanLySanPhamEntities2();

            CategoriesFiveTeam categories = db.CategoriesFiveTeams.Find(id);
            return View(categories);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CategoriesCode,CategoriesName,SellOff,Picture")] CategoriesFiveTeam categories, HttpPostedFileBase fileAnh)
        {
            QuanLySanPhamEntities2 db = new QuanLySanPhamEntities2();
            if (ModelState.IsValid)
            {
                if (fileAnh != null && fileAnh.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(fileAnh.FileName);
                    string filePath = Path.Combine(Server.MapPath("~/img/Categories/"), fileName);
                    fileAnh.SaveAs(filePath);
                    categories.Picture = "~/img/Categories/" + fileName;
                }

                db.Entry(categories).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListCategories");
            }

            return View(categories);
        }


        /* Xóa sản phẩm*/
        public ActionResult Delete(int id)
        {
            QuanLySanPhamEntities2 db = new QuanLySanPhamEntities2();
            var updateModel = db.CategoriesFiveTeams.Find(id);
            db.CategoriesFiveTeams.Remove(updateModel);
            db.SaveChanges();

            return RedirectToAction("ListCategories");
        }


        // Chi tiết sản phẩm/
        public ActionResult Details(int? id)
        {
            QuanLySanPhamEntities2 db = new QuanLySanPhamEntities2();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriesFiveTeam categories = db.CategoriesFiveTeams.Find(id);
            if (categories == null)
            {
                return HttpNotFound();
            }

            return View(categories);
        }

    }
}

FiveTeam/Areas/AdminHome/Views/AdminCategories/Create.cshtml
@model FiveTeam.Models.CategoriesFiveTeam

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminHome/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Các thuộc tính chung */
    .heading {
        font-weight: bolder;
        text-align: center;
        padding: 5rem 0 2rem; /* Kết hợp padding thành một dòng */
        font-size: 3.5rem;
        color: var(--black);
    }

        /* Hiệu ứng cho phần chữ trong thẻ <span> của .heading */
        .heading span {
            background: #FF8C00;
            color: #fff;
            display: inline-block;
            padding: .5rem 3rem;
            clip-path: polygon(100% 0, 93% 50%, 100% 99%, 0% 100%, 7% 50%, 0% 0%);
        }

    /* Phần form */
    .form-horizontal, h2, h4 {
        width: 60%;
        margin: 0 auto;
        line-height: 1.5rem;
        border-radius: .5rem;
        background: #eee;
        color: var(--black);
        font-size: 1.5rem;
        font-weight: bolder;
    }

    .form-group {
        margin-bottom: 10px;
    }

    .control-label {
        text-align: right;
    }

    .col-md-10 {
        padding: 0;
    }

    .form-control {
        background-color: #eee;
        font-size: 1.5rem;
        width: 90%;
    }

        .form-control:hover {
            color: var(--orange); /* Loại bỏ dòng trùng lặp */
            cursor: pointer;
        }

    /* Nút */
    .btn-default {
        padding: 0.5rem 1rem;
        font-size: 1.5rem;
        border-radius: 0.5rem;
        font-weight: bolder;
        color: #FF8C00;
    }

        /* Hover state cho nút */
        .btn-default:hover {
            background-color: var(--orange);
        }

    h3 {
        width: 60%;
        margin: 0 auto;
        font-size: 3rem;
        font-weight: bolder;
        color: #FF8C00;
    }

    /* Đặt màu chữ cho nút */
    .btn-default {
        color: #FF8C00;
    }
</style>

<h1 class="heading" style="color: #000080"> Tạo <span>Giảm Giá</span> </h1>
<h3>Gia Vị Việt
    </h3>

@using (Html.BeginForm("Create", "AdminCategories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="color: #000080">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriesCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoriesCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoriesCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriesName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoriesName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoriesName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SellOff, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SellOff, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SellOff, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="fileAnh" class="form-control" />
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 ">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>

            <div class="col-md-offset-2 ">
                @Html.ActionLink("Back to List", "ListCategories", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

FiveTeam/Areas/AdminHome/Views/AdminCategories/Delete.cshtml
@model FiveTeam.Models.CategoriesFiveTeam

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/AdminHome/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CategoriesFiveTeam</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoriesCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoriesCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoriesName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoriesName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SellOff)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SellOff)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FiveTeam/Areas/AdminHome/Views/AdminCategories/Details.cshtml
@model FiveTeam.Models.CategoriesFiveTeam

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/AdminHome/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .heading {
        font-weight: bolder;
        text-align: center;
        padding: 2rem 0;
        padding-top: 5rem;
        font-size: 3.5rem;
        color: var(--black);
    }

        /* Tạo hiệu ứng nổi bật cho phần chữ trong thẻ <span> của .heading */
        .heading span {
            background: #FF8C00;
            color: #fff;
            display: inline-block;
            padding: .5rem 3rem;
            clip-path: polygon(100% 0, 93% 50%, 100% 99%, 0% 100%, 7% 50%, 0% 0%);
        }

    .dl-horizontal {
        width: 60%;
        margin: 0 auto;
        border-radius: .5rem;
        background: #eee;
        color: var(--black);
    }

    .form-group {
        margin-bottom: 15px;
        padding: 2px;
        width: 50%;
        margin: 0 auto;
        border-radius: .5rem;
        background: #eee;
        color: #FF8C00;
        font-size: 1.5rem;
        font-weight: bolder;
    }

    dt {
        margin-bottom: 15px;
        font-size: 1.5rem;
        font-weight: bolder;
    }

    dd {
        margin-bottom: 10px;
        font-size: 1.5rem;
        cursor: pointer;
    }

    h3 {
        width: 50%; /* Đặt chiều rộng mong muốn của bảng */
        margin: 0 auto;
        font-size: 3rem;
        color: #FF8C00;
    }

    .bnt {
        margin-top: .5rem;
        display: inline-block;
        padding: .8rem 2rem;
        font-size: 1.7rem;
        border-radius: .5rem;
        cursor: pointer;
        background: none; /* Chưa có giá trị nền */
        font-weight: bolder;
        margin: 0 auto;
    }

    /* Định nghĩa các thuộc tính CSS cho class .btn-default */
    .btn-default {
        padding: 0.5rem 1rem;
        font-size: 1.5rem;
        border-radius: 0.5rem;
        font-weight: bolder;
        color: #FF8C00;
    }

    /* Định nghĩa các thuộc tính CSS cho class .bnt btn-default khi hover */
    .bnt btn-default:hover {
        background-color: var(--orange);
        color: #FF8C00;
    }
    h3 {
        width: 60%;
        margin: 0 auto;
        font-size: 3rem;
        font-weight: bolder;
        color: #FF8C00;
    }
</style>

<h1 class="heading" style="color: #000080"> Thông Tin <span>Giảm Giá</span> </h1>
<h3>Gia Vị Việt</h3>
<div>
    <hr />
    <dl class="dl-horizontal" style="color: #000080">
        <dt>
            @Html.DisplayNameFor(model => model.CategoriesCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoriesCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoriesName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoriesName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SellOff)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SellOff)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

    </dl>
    <div class="">
        <div class="col-md-6 col-md-offset-3 text-left">
            <!-- Sử dụng col-md-6 và col-md-offset-3 để căn giữa và giữ cùng một hàng -->
            <div class="text-center">
                <!-- Thêm text-center để căn giữa nội dung -->
                @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { @class = "btn btn-default" })
                @Html.ActionLink("Back to List", "ListCategories", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>

</div>

FiveTeam/Areas/AdminHome/Views/AdminCategories/Edit.cshtml
@model FiveTeam.Models.CategoriesFiveTeam

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminHome/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Các thuộc tính chung cho .heading */
    .heading {
        font-weight: bolder; /* Đặt độ đậm cho font */
        text-align: center; /* Canh giữa văn bản */
        font-size: 3.5rem; /* Kích thước font */
        color: var(--black); /* Màu chữ */
        padding: 5rem 0 2rem; /* Padding: trên dưới 5rem, bên trong 0, dưới 2rem */
    }

        /* Hiệu ứng cho phần chữ trong thẻ <span> của .heading */
        .heading span {
            background: #FF8C00; /* Màu nền cho span */
            color: #fff; /* Màu chữ cho span */
            display: inline-block; /* Hiển thị như một khối, không đẩy xuống dòng */
            padding: .5rem 3rem; /* Padding cho span */
            clip-path: polygon(100% 0, 93% 50%, 100% 99%, 0% 100%, 7% 50%, 0% 0%); /* Định dạng dạng hình */
        }

    /* Phần form */
    .form-horizontal {
        width: 60%; /* Độ rộng của các thành phần form */
        margin: 0 auto; /* Canh giữa */
        line-height: 1.5rem; /* Chiều cao dòng */
        border-radius: .5rem; /* Bo tròn góc */
        background: #eee; /* Màu nền */
        color: var(--black); /* Màu chữ */
        font-size: 1.5rem; /* Kích thước font */
        font-weight: bolder; /* Độ đậm cho font */
        align-items: center;
        margin-top: 10px; /* Khoảng cách trên */
    }

    .form-group {
        margin-bottom: 10px; /* Khoảng cách dưới */
    }

    .control-label {
        text-align: right; /* Canh phải */
        margin-top: 10px; /* Khoảng cách trên */
    }

    .col-md-10 {
        padding: 0; /* Xóa padding */
        margin-bottom: 10px; /* Khoảng cách dưới */
    }

    .form-control {
        background-color: #eee; /* Màu nền cho control */
        font-size: 1.5rem; /* Kích thước font */
        width: 90%; /* Độ rộng */
    }

        .form-control:hover {
            color: var(--orange); /* Màu chữ hover */
            cursor: pointer; /* Con trỏ chuột */
        }

    /* Nút */
    .btn-default {
        padding: 0.5rem 1rem; /* Padding cho nút */
        font-size: 1.5rem; /* Kích thước font */
        border-radius: 0.5rem; /* Bo tròn góc */
        font-weight: bolder; /* Độ đậm cho font */
        color: #FF8C00; /* Màu chữ */
    }

        .btn-default:hover {
            background-color: var(--orange); /* Màu nền hover */
        }

    /* Nút .bnt */
    .bnt {
        margin-top: 1rem; /* Khoảng cách trên */
        display: inline-block; /* Hiển thị inline-block */
        padding: .8rem 3rem; /* Padding */
        font-size: 1.7rem; /* Kích thước font */
        border-radius: .5rem; /* Bo tròn góc */
        border: .2rem solid var(--black); /* Đường viền */
        cursor: pointer; /* Con trỏ chuột */
        background: none; /* Không có giá trị nền */
        font-weight: bolder; /* Độ đậm cho font */
    }

        .bnt:hover {
            background-color: var(--orange); /* Màu nền hover */
            color: #FF8C00; /* Màu chữ hover */
        }

    h3 {
        width: 50%; /* Độ rộng của tiêu đề h3 */
        margin: 0 auto; /* Canh giữa */
        font-size: 3rem; /* Kích thước font */
        font-weight: bolder; /* Độ đậm cho font */
        color: #FF8C00; /* Màu chữ */
    }
</style>

<h1 class="heading" style="color: #000080"> Sửa <span>Giảm Giá</span> </h1>
<h3>Gia Vị Việt</h3>

@using (Html.BeginForm("Edit", "AdminCategories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="color: #000080">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriesCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoriesCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoriesCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriesName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoriesName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoriesName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SellOff, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SellOff, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SellOff, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="fileAnh" class="form-control" />
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="">
            <div class="col-md-6 col-md-offset-3 text-left ">
                <div class="text-center">
                    <input type="submit" value="Save" class="btn btn-default" />
                    @Html.ActionLink("Back to List", "ListCategories", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>


    </div>
}

FiveTeam/Areas/AdminHome/Views/AdminCategories/ListCategories.cshtml
@model IEnumerable<FiveTeam.Models.CategoriesFiveTeam>

@{
    ViewBag.Title = "ListCategories";
    Layout = "~/Areas/AdminHome/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Định nghĩa các thuộc tính CSS cho class .heading */
    .heading {
        font-weight: bolder;
        text-align: center;
        padding: 2rem 0;
        padding-top: 5rem;
        font-size: 3.5rem;
        color: var(--black);
    }

        /* Tạo hiệu ứng nổi bật cho phần chữ trong thẻ <span> của .heading */
        .heading span {
            background: #FF8C00;
            color: #fff;
            display: inline-block;
            padding: .5rem 3rem;
            clip-path: polygon(100% 0, 93% 50%, 100% 99%, 0% 100%, 7% 50%, 0% 0%);
        }

    /* Định nghĩa các thuộc tính CSS cho class .alert */
    .alert {
        /* Thêm class alert-success vào đây */
        width: 60%;
        font-weight: bolder;
        color: #FF8C00;
    }

    /* Định nghĩa các thuộc tính CSS cho class .table-container và thẻ p */
    .table-container, p {
        width: 60%;
        margin: 0 auto;
    }

    /* Định nghĩa các thuộc tính CSS cho thẻ table */
    table {
        border-collapse: collapse;
        width: 100%;
    }

    /* Định nghĩa các thuộc tính CSS cho thẻ tr */
    tr {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    /* Định nghĩa các thuộc tính CSS cho thẻ th */
    th {
        font-size: 1.5rem;
        font-weight: bolder;
        color: var(--black);
    }

    /* Định nghĩa các thuộc tính CSS cho thẻ td */
    td {
        font-size: 1.5rem;
        color: var(--black);
    }

    /* Định nghĩa các thuộc tính CSS cho class .bnt */
    .bnt {
        margin-top: 1rem;
        display: inline-block;
        padding: .8rem 3rem;
        font-size: 1.7rem;
        border-radius: .5rem;
        border: .2rem solid var(--black);
        cursor: pointer;
        background:; /* Chưa có giá trị nền */
        font-weight: bolder;
    }

    /* Định nghĩa các thuộc tính CSS cho class .btn-default */
    .btn-default {
        padding: 0.5rem 1rem;
        font-size: 1.5rem;
        border-radius: 0.5rem;
        font-weight: bolder;
        color: #FF8C00;
    }

    /* Định nghĩa các thuộc tính CSS cho class .bnt btn-default khi hover */
    .bnt btn-default:hover {
        background-color: var(--orange);
        color: #FF8C00;
    }

    /* Định nghĩa các thuộc tính CSS cho thẻ h3 */
    h3 {
        width: 60%;
        margin: 0 auto;
        font-size: 3rem;
        font-weight: bolder;
        color: #FF8C00;
    }
</style>

<h1 class="heading" style="color: #000080"> Danh Sách <span>Giảm Giá</span> </h1>
<h1 class="heading"> @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-default" }) </h1>
<h3>Gia Vị Việt</h3>
<div class="table-container" style="color: #000080">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoriesCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoriesName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SellOff)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoriesCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoriesName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SellOff)
                </td>
                <td>
                    <img src="@Url.Content(item.Picture)"
                         alt="Image"
                         width="100"
                         height="100" />
                </td>
                <td class="default" style="text-align: right;">
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-default" })
                </td>
            </tr>
        }

    </table>
</div>